[build]
  functions = "netlify/functions/"
  publish = "Imagen/"

[functions]
  node_bundler = "esbuild"

[[plugins]]
package = "@netlify/plugin-image-optimization"

[[plugins]]
package = "netlify-plugin-google-analytics"

[[plugins]]
package = "@netlify/plugin-netlify-cms"

[[plugins]]
package = "netlify-plugin-inline-functions-env"

