[build]
  command = "npm run build"
  publish = "public/"

[build.environment]
  NODE_ENV = "production"
  
[functions]
  node_bundler = "esbuild"

[[plugins]]
package = "@netlify/plugin-image-optimization"

[[plugins]]
package = "netlify-plugin-google-analytics"

[[plugins]]
package = "@netlify/plugin-netlify-cms"
