[build]
  publish = "public"
  command = "gatsby build"

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex, noarchive"
    Cache-Control = "no-cache, no-store, must-revalidate"

[[plugins]]
  package = "@netlify/plugin-inline-functions-env"
